java_binary(
    name = "contest-manager",
    srcs = glob(["src/main/java/**/*.java"]),
    main_class = "io.zulus.cm.ZulusContestManagerApplication",
    deps = [
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure",
        "@maven//:org_springframework_boot_spring_boot_starter_security",
        "@maven//:org_springframework_boot_spring_boot_starter_jdbc",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jpa",
    ]
)
